### PR TITLE
feat: `IsFocusWithin`

### PR DESCRIPTION
**Pull request by huntabyte**
Tracks whether focus is within a given target element.

```svelte
<script lang="ts">
	import { IsFocusWithin } from 'runed'

	let formElement = $state<HTMLElement | undefined>()
	const focusWithinForm = new IsFocusWithin(() => formElement)
</script>

<span>Focus is within: {focusWithinForm.current}</span>
<form bind:this={formElement}>
	<input />
</form>
```

I also added testing library so we can test components.

### CODE REVIEW

**Comment by abdel-17** [comment]
I feel like this might encourage relying on JS for styling instead of just the `:focus-within` selector.

**Comment by huntabyte** [comment]
> I feel like this might encourage relying on JS for styling instead of just the `:focus-within` selector.

The same could be said for the `activeElement` instead of focus. The intentions aren't for it to be used for styling but rather side effects when focus is/isn't within a specific element which is useful.

**Comment by huntabyte** [comment]
Also, there is a use case for styling where you want to style something that isn't the form element differently when the form element has focus within.

**Comment by abdel-17** [comment]
> Also, there is a use case for styling where you want to style something that isn't the form element differently when the form element has focus within.

You can still use CSS for that.

Style a child
`form:focus-within .some-selector`

Style a sibling
`form:focus-within + .some-selector`

Style a parent
`.some-selector:has(form:focus-within)'

But yeah I get the other use case.

**Review by AdrianGonz97 — APPROVED** [review]

**Pull request merged**
